index = {'accede': ['exceed'],
 'accept': ['except'],
 'access': ['excess'],
 'accessary': ['accessory'],
 'accessory': ['accessary'],
 'ad': ['add'],
 'adapt': ['adept', 'adopt'],
 'add': ['ad'],
 'adept': ['adapt', 'adopt'],
 'adopt': ['adapt', 'adept'],
 'advice': ['advise'],
 'advise': ['advice'],
 'aerie': ['airy', 'eerie'],
 'aid': ['aide'],
 'aide': ['aid'],
 'ail': ['ale'],
 'air': ['ere', 'heir'],
 'airy': ['aerie', 'eerie'],
 'aisle': ["i'll", 'isle'],
 'ale': ['ail'],
 'all': ['awl'],
 'alley': ['ally'],
 'allowed': ['aloud'],
 'allready': ['already'],
 'allude': ['elude'],
 'allusion': ['illusion'],
 'ally': ['alley'],
 'alms': ['arms'],
 'aloud': ['allowed'],
 'already': ['allready'],
 'altar': ['alter'],
 'alter': ['altar'],
 'ant': ["aren't", 'aunt'],
 'appraise': ['apprise'],
 'apprise': ['appraise'],
 'arc': ['ark'],
 "aren't": ['ant', 'aunt'],
 'ark': ['arc'],
 'arms': ['alms'],
 'ascent': ['assent'],
 'assay': ['essay'],
 'assent': ['ascent'],
 'ate': ['eight'],
 'attendance': ['attendants'],
 'attendants': ['attendance'],
 'auger': ['augur'],
 'aught': ['ought'],
 'augur': ['auger'],
 'auk': ['orc'],
 'aunt': ['ant', "aren't"],
 'aural': ['oral'],
 'auricle': ['oracle'],
 'average': ['median', 'normal'],
 'away': ['aweigh'],
 'awe': ['oar', 'oh', 'or', 'ore', 'owe'],
 'aweigh': ['away'],
 'awl': ['all'],
 'axel': ['axle'],
 'axes': ['axis'],
 'axis': ['axes'],
 'axle': ['axel'],
 'aye': ['eye', 'i'],
 'bail': ['bale'],
 'bait': ['bate'],
 'baited': ['bated'],
 'baize': ['bays'],
 'bald': ['bawled'],
 'bale': ['bail'],
 'ball': ['bawl'],
 'band': ['banned'],
 'banned': ['band'],
 'bard': ['barred'],
 'bare': ['bear'],
 'bark': ['barque'],
 'baron': ['barren'],
 'barque': ['bark'],
 'barred': ['bard'],
 'barren': ['baron'],
 'base': ['bass'],
 'based': ['baste'],
 'bases': ['basis'],
 'basis': ['bases'],
 'bass': ['base'],
 'baste': ['based'],
 'bate': ['bait'],
 'bated': ['baited'],
 'bawl': ['ball'],
 'bawled': ['bald'],
 'bay': ['bey'],
 'bays': ['baize'],
 'bazaar': ['bizarre'],
 'be': ['bee'],
 'beach': ['beech'],
 'bean': ['been'],
 'bear': ['bare'],
 'beat': ['beet'],
 'beau': ['bough', 'bow'],
 'bee': ['be'],
 'beech': ['beach'],
 'been': ['bean'],
 'beer': ['bier'],
 'beet': ['beat'],
 'bel': ['bell', 'belle'],
 'bell': ['bel', 'belle'],
 'belle': ['bel', 'bell'],
 'berry': ['bury'],
 'berth': ['birth'],
 'bey': ['bay'],
 'bier': ['beer'],
 'bight': ['bite', 'byte'],
 'billed': ['build'],
 'birth': ['berth'],
 'bite': ['bight', 'byte'],
 'bitten': ['bittern'],
 'bittern': ['bitten'],
 'bizarre': ['bazaar'],
 'blew': ['blue'],
 'bloc': ['block'],
 'block': ['bloc'],
 'blue': ['blew'],
 'boar': ['bore'],
 'board': ['bored'],
 'boarder': ['border'],
 'bold': ['bowled'],
 'bolder': ['boulder'],
 'boos': ['booze'],
 'bootie': ['booty'],
 'booty': ['bootie'],
 'booze': ['boos'],
 'border': ['boarder'],
 'bore': ['boar'],
 'bored': ['board'],
 'born': ['borne'],
 'borne': ['born'],
 'borough': ['burro', 'burrow'],
 'bough': ['beau', 'bow'],
 'bouillon': ['bullion'],
 'boulder': ['bolder'],
 'bow': ['beau', 'bough'],
 'bowled': ['bold'],
 'boy': ['buoy'],
 'brae': ['bray'],
 'braid': ['brayed'],
 'braise': ['brays', 'braze'],
 'brake': ['break'],
 'bray': ['brae'],
 'brayed': ['braid'],
 'brays': ['braise', 'braze'],
 'braze': ['braise', 'brays'],
 'breach': ['breech'],
 'bread': ['bred'],
 'break': ['brake'],
 'bred': ['bread'],
 'breech': ['breach'],
 'brewed': ['brood'],
 'brews': ['bruise'],
 'bridal': ['bridle'],
 'bridle': ['bridal'],
 'bring': ['take'],
 'broach': ['brooch'],
 'brooch': ['broach'],
 'brood': ['brewed'],
 'brows': ['browse'],
 'browse': ['brows'],
 'bruise': ['brews'],
 'build': ['billed'],
 'bullion': ['bouillon'],
 'buoy': ['boy'],
 'bur': ['burr'],
 'burr': ['bur'],
 'burro': ['borough', 'burrow'],
 'burrow': ['borough', 'burro'],
 'bury': ['berry'],
 'but': ['butt'],
 'butt': ['but'],
 'buy': ['by', 'bye'],
 'buyer': ['byre'],
 'by': ['buy', 'bye'],
 'bye': ['buy', 'by'],
 'byre': ['buyer'],
 'byte': ['bight', 'bite'],
 'caddie': ['caddy'],
 'caddy': ['caddie'],
 'calendar': ['calender'],
 'calender': ['calendar'],
 'call': ['caul'],
 'callous': ['callus'],
 'callus': ['callous'],
 'cannon': ['canon'],
 'canon': ['cannon'],
 'canter': ['cantor'],
 'cantor': ['canter'],
 'canvas': ['canvass'],
 'canvass': ['canvas'],
 'capital': ['capitol'],
 'capitol': ['capital'],
 'carat': ['carrot'],
 'carol': ['carrel'],
 'carrel': ['carol'],
 'carrot': ['carat'],
 'cast': ['caste'],
 'caste': ['cast'],
 'caster': ['castor'],
 'castor': ['caster'],
 'caught': ['court'],
 'caul': ['call'],
 'caw': ['core', 'corps'],
 'cede': ['seed'],
 'ceiling': ['sealing'],
 'cell': ['sell'],
 'cellar': ['seller'],
 'censer': ['censor', 'censure', 'sensor'],
 'censor': ['censer', 'censure', 'sensor'],
 'censure': ['censer', 'censor', 'sensor'],
 'census': ['sense'],
 'cent': ['scent', 'sent'],
 'cereal': ['serial'],
 'cession': ['session'],
 'chance': ['chants'],
 'chantey': ['shanty'],
 'chants': ['chance'],
 'chased': ['chaste'],
 'chaste': ['chased'],
 'cheap': ['cheep'],
 'check': ['cheque'],
 'cheep': ['cheap'],
 'cheque': ['check'],
 'chews': ['choose'],
 'chic': ['sheik'],
 'chile': ['chili', 'chilli', 'chilly'],
 'chili': ['chile', 'chilli', 'chilly'],
 'chilli': ['chile', 'chili', 'chilly'],
 'chilly': ['chile', 'chili', 'chilli'],
 'choir': ['quire'],
 'choose': ['chews'],
 'choral': ['coral'],
 'chord': ['cord', 'cored'],
 'chute': ['shoot'],
 'cite': ['sight', 'site'],
 'clack': ['claque'],
 'claque': ['clack'],
 'clause': ['claws'],
 'claws': ['clause'],
 'clew': ['clue'],
 'climb': ['clime'],
 'clime': ['climb'],
 'close': ['clothes', 'cloze'],
 'clothes': ['close', 'cloze'],
 'cloze': ['close', 'clothes'],
 'clue': ['clew'],
 'coal': ['kohl'],
 'coarse': ['course'],
 'coign': ['coin'],
 'coin': ['coign'],
 'colonel': ['kernel'],
 'complacent': ['complaisant'],
 'complaisant': ['complacent'],
 'complement': ['compliment'],
 'compliment': ['complement'],
 'confidant': ['confident'],
 'confident': ['confidant'],
 'coo': ['coup'],
 'cops': ['copse'],
 'copse': ['cops'],
 'coral': ['choral'],
 'cord': ['chord', 'cored'],
 'core': ['caw', 'corps'],
 'cored': ['chord', 'cord'],
 'corps': ['caw', 'core'],
 'council': ['counsel'],
 'counsel': ['council'],
 'coup': ['coo'],
 'course': ['coarse'],
 'court': ['caught'],
 'cousin': ['cozen'],
 'coward': ['cowered'],
 'cowered': ['coward'],
 'cozen': ['cousin'],
 'creak': ['creek'],
 'creek': ['creak'],
 'crewel': ['cruel'],
 'crews': ['cruise'],
 'cruel': ['crewel'],
 'cruise': ['crews'],
 'cue': ['kyu', 'queue'],
 'curb': ['kerb'],
 'currant': ['current'],
 'current': ['currant'],
 'cygnet': ['signet'],
 'cymbal': ['cymbol', 'symbol'],
 'cymbol': ['cymbal', 'symbol'],
 'dam': ['damn'],
 'damn': ['dam'],
 'days': ['daze'],
 'daze': ['days'],
 'dear': ['deer'],
 'deer': ['dear'],
 'dense': ['dents'],
 'dents': ['dense'],
 'depravation': ['deprivation'],
 'deprivation': ['depravation'],
 'descent': ['dissent'],
 'desert': ['dessert'],
 'desperate': ['disparate'],
 'dessert': ['desert'],
 'deviser': ['divisor'],
 'dew': ['do', 'due'],
 'die': ['dye'],
 'disburse': ['disperse'],
 'discreet': ['discrete'],
 'discrete': ['discreet'],
 'disparate': ['desperate'],
 'disperse': ['disburse'],
 'dissent': ['descent'],
 'divisor': ['deviser'],
 'do': ['dew', 'due'],
 'doe': ['doh', 'dough'],
 'does': ['doze'],
 'doh': ['doe', 'dough'],
 'done': ['dun'],
 'dough': ['doe', 'doh'],
 'douse': ['dowse'],
 'dowse': ['douse'],
 'doze': ['does'],
 'draft': ['draught'],
 'draught': ['draft'],
 'dual': ['duel'],
 'due': ['dew', 'do'],
 'duel': ['dual'],
 'dun': ['done'],
 'dye': ['die'],
 'dyeing': ['dying'],
 'dying': ['dyeing'],
 'each': ['either'],
 'earn': ['urn'],
 'eave': ['eve'],
 'ecology': ['environment'],
 'eek': ['eke'],
 'eerie': ['aerie', 'airy'],
 'eery': ['eyrie'],
 'eight': ['ate'],
 'either': ['each'],
 'eke': ['eek'],
 'elicit': ['illicit'],
 'elude': ['allude'],
 'eminent': ['imminent'],
 'environment': ['ecology'],
 'epic': ['epoch'],
 'epoch': ['epic'],
 'ere': ['air', 'heir'],
 'essay': ['assay'],
 'eve': ['eave'],
 'ewe': ['yew', 'you'],
 'ewes': ['use', 'yews'],
 'exceed': ['accede'],
 'except': ['accept'],
 'excess': ['access'],
 'extant': ['extent'],
 'extent': ['extant'],
 'eye': ['aye', 'i'],
 'eyelet': ['islet'],
 'eyrie': ['eery'],
 'facts': ['fax'],
 'fah': ['far'],
 'fain': ['feign'],
 'faint': ['feint'],
 'fair': ['fare'],
 'fairy': ['ferry'],
 'far': ['fah'],
 'fare': ['fair'],
 'farther': ['father'],
 'father': ['farther'],
 'faun': ['fawn'],
 'fawn': ['faun'],
 'fax': ['facts'],
 'fay': ['fey'],
 'faze': ['phase'],
 'feat': ['feet', 'fete'],
 'feet': ['feat', 'fete'],
 'feign': ['fain'],
 'feint': ['faint'],
 'ferrule': ['ferule'],
 'ferry': ['fairy'],
 'ferule': ['ferrule'],
 'fete': ['feat', 'feet'],
 'few': ['phew'],
 'fey': ['fay'],
 'fie': ['phi'],
 'file': ['phial'],
 'find': ['fined'],
 'fined': ['find'],
 'fir': ['fur'],
 'fisher': ['fissure'],
 'fissure': ['fisher'],
 'fizz': ['phiz'],
 'flair': ['flare'],
 'flare': ['flair'],
 'flaw': ['floor'],
 'flea': ['flee'],
 'flecks': ['flex'],
 'flee': ['flea'],
 'flew': ['flu', 'flue'],
 'flex': ['flecks'],
 'floe': ['flow'],
 'floor': ['flaw'],
 'flour': ['flower'],
 'flow': ['floe'],
 'flower': ['flour'],
 'flu': ['flew', 'flue'],
 'flue': ['flew', 'flu'],
 'foaled': ['fold'],
 'fold': ['foaled'],
 'for': ['fore', 'forth', 'four', 'fourth'],
 'forbear': ['forebear'],
 'fore': ['for', 'forth', 'four', 'fourth'],
 'forebear': ['forbear'],
 'foreword': ['forward'],
 'formally': ['formerly'],
 'formerly': ['formally'],
 'fort': ['fought'],
 'forth': ['for', 'fore', 'four', 'fourth'],
 'forward': ['foreword'],
 'fought': ['fort'],
 'foul': ['fowl'],
 'four': ['for', 'fore', 'forth', 'fourth'],
 'fourth': ['for', 'fore', 'forth', 'four'],
 'fowl': ['foul'],
 'franc': ['frank'],
 'frank': ['franc'],
 'frays': ['phrase'],
 'freeze': ['frieze'],
 'friar': ['fryer'],
 'frieze': ['freeze'],
 'fryer': ['friar'],
 'fur': ['fir'],
 'furs': ['furze'],
 'furze': ['furs'],
 'gaff': ['gaffe'],
 'gaffe': ['gaff'],
 'gage': ['gauge'],
 'gait': ['gate'],
 'galipot': ['gallipot'],
 'gallipot': ['galipot'],
 'gallop': ['galop'],
 'galop': ['gallop'],
 'gamble': ['gambol'],
 'gambol': ['gamble'],
 'gate': ['gait'],
 'gauge': ['gage'],
 'gays': ['gaze'],
 'gaze': ['gays'],
 'gel': ['jell'],
 'gene': ['jean'],
 'genes': ['jeans'],
 'genius': ['genus'],
 'genus': ['genius'],
 'gibe': ['jibe'],
 'gild': ['guild'],
 'gilt': ['guilt'],
 'giro': ['gyro'],
 'gist': ['jest'],
 'glacier': ['glazier'],
 'glazier': ['glacier'],
 'gnaw': ['naw', 'nor'],
 'gneiss': ['nice'],
 'gnu': ['knew', 'new'],
 'gofer': ['gopher'],
 'gopher': ['gofer'],
 'gored': ['gourd'],
 'gorilla': ['guerilla', 'guerrilla'],
 'gourd': ['gored'],
 'grate': ['great'],
 'graze': ['greys'],
 'grease': ['greece'],
 'great': ['grate'],
 'greave': ['grieve'],
 'greece': ['grease'],
 'greys': ['graze'],
 'grieve': ['greave'],
 'grill': ['grille'],
 'grille': ['grill'],
 'grisly': ['grizzly'],
 'grizzly': ['grisly'],
 'groan': ['grown'],
 'grown': ['groan'],
 'guarantee': ['guaranty'],
 'guaranty': ['guarantee'],
 'guerilla': ['gorilla', 'guerrilla'],
 'guerrilla': ['gorilla', 'guerilla'],
 'guessed': ['guest'],
 'guest': ['guessed'],
 'guild': ['gild'],
 'guilt': ['gilt'],
 'guise': ['guys'],
 'guys': ['guise'],
 'gyro': ['giro'],
 'hail': ['hale'],
 'hair': ['hare'],
 'hairier': ['harrier'],
 'hale': ['hail'],
 'hall': ['haul'],
 'halve': ['have'],
 'handsome': ['hansom'],
 'hangar': ['hanger'],
 'hanger': ['hangar'],
 'hansom': ['handsome'],
 'hare': ['hair'],
 'harrier': ['hairier'],
 'hart': ['heart'],
 'haul': ['hall'],
 'have': ['halve'],
 'haw': ['hoar', 'whore'],
 'hay': ['hey'],
 "he'd": ['heed'],
 "he'll": ['heal', 'heel'],
 'heal': ["he'll", 'heel'],
 'hear': ['here'],
 'heard': ['herd'],
 'heart': ['hart'],
 'heed': ["he'd"],
 'heel': ["he'll", 'heal'],
 'heir': ['air', 'ere'],
 'herd': ['heard'],
 'here': ['hear'],
 'heroin': ['heroine'],
 'heroine': ['heroin'],
 'hew': ['hue'],
 'hey': ['hay'],
 'hi': ['high'],
 'high': ['hi'],
 'higher': ['hire'],
 'him': ['hymn'],
 'hire': ['higher'],
 'ho': ['hoe'],
 'hoar': ['haw', 'whore'],
 'hoard': ['horde'],
 'hoarse': ['horse'],
 'hoe': ['ho'],
 'hoes': ['hose'],
 'hole': ['whole'],
 'holey': ['holy', 'wholly'],
 'holy': ['holey', 'wholly'],
 'hoop': ['whoop'],
 'horde': ['hoard'],
 'horse': ['hoarse'],
 'hose': ['hoes'],
 'hostel': ['hostile'],
 'hostile': ['hostel'],
 'hour': ['our'],
 'hue': ['hew'],
 'humerus': ['humorous'],
 'humorous': ['humerus'],
 'hurdle': ['hurtle'],
 'hurtle': ['hurdle'],
 'hymn': ['him'],
 'hypercritical': ['hypocritical'],
 'hypocritical': ['hypercritical'],
 'i': ['aye', 'eye'],
 "i'll": ['aisle', 'isle'],
 'idle': ['idol', 'idyll'],
 'idol': ['idle', 'idyll'],
 'idyll': ['idle', 'idol'],
 'illicit': ['elicit'],
 'illusion': ['allusion'],
 'imminent': ['eminent'],
 'in': ['inn'],
 'incidence': ['incidents'],
 'incidents': ['incidence'],
 'incite': ['insight'],
 'incredible': ['incredulous'],
 'incredulous': ['incredible'],
 'indict': ['indite'],
 'indite': ['indict'],
 'inequity': ['iniquity'],
 'ingenious': ['ingenuous'],
 'ingenuous': ['ingenious'],
 'iniquity': ['inequity'],
 'inn': ['in'],
 'insight': ['incite'],
 'intense': ['intents'],
 'intents': ['intense'],
 'interstate': ['intrastate'],
 'intrastate': ['interstate'],
 'isle': ['aisle', "i'll"],
 'islet': ['eyelet'],
 "it's": ['its'],
 'its': ["it's"],
 'jalousie': ['jealousy'],
 'jam': ['jamb'],
 'jamb': ['jam'],
 'jealousy': ['jalousie'],
 'jean': ['gene'],
 'jeans': ['genes'],
 'jell': ['gel'],
 'jest': ['gist'],
 'jewel': ['joule'],
 'jibe': ['gibe'],
 'joule': ['jewel'],
 'judicial': ['judicious'],
 'judicious': ['judicial'],
 'kerb': ['curb'],
 'kernel': ['colonel'],
 'key': ['quay'],
 'kill': ['kiln'],
 'kiln': ['kill'],
 'knave': ['nave'],
 'knead': ['kneed', 'need'],
 'kneed': ['knead', 'need'],
 'knew': ['gnu', 'new'],
 'knight': ['night'],
 'knit': ['nit'],
 'knob': ['nob'],
 'knock': ['nock'],
 'knot': ['not'],
 'know': ['no'],
 'knows': ['nose'],
 'kohl': ['coal'],
 'kyu': ['cue', 'queue'],
 'laager': ['lager'],
 'lac': ['lack'],
 'lack': ['lac'],
 'lacks': ['lax'],
 'lade': ['laid'],
 'lager': ['laager'],
 'laid': ['lade'],
 'lain': ['lane'],
 'lam': ['lamb'],
 'lama': ['llama'],
 'lamb': ['lam'],
 'lane': ['lain'],
 'laps': ['lapse'],
 'lapse': ['laps'],
 'larva': ['lava'],
 'lase': ['laze'],
 'lava': ['larva'],
 'law': ['lore'],
 'lax': ['lacks'],
 'lay': ['lei', 'ley'],
 'laze': ['lase'],
 'lea': ['lee'],
 'leach': ['leech'],
 'lead': ['led'],
 'leak': ['leek'],
 'lean': ['lien'],
 'leased': ['least'],
 'least': ['leased'],
 'led': ['lead'],
 'lee': ['lea'],
 'leech': ['leach'],
 'leek': ['leak'],
 'lei': ['lay', 'ley'],
 'lessen': ['lesson'],
 'lesser': ['lessor'],
 'lesson': ['lessen'],
 'lessor': ['lesser'],
 'levee': ['levy'],
 'levy': ['levee'],
 'ley': ['lay', 'lei'],
 'liable': ['libel'],
 'liar': ['lyre'],
 'libel': ['liable'],
 'licence': ['license'],
 'license': ['licence'],
 'lichen': ['liken'],
 'licker': ['liquor'],
 'lie': ['lye'],
 'lien': ['lean'],
 'lieu': ['loo'],
 'liken': ['lichen'],
 'links': ['lynx'],
 'liquor': ['licker'],
 'literal': ['littoral'],
 'littoral': ['literal'],
 'llama': ['lama'],
 'lo': ['low'],
 'load': ['lode'],
 'loan': ['lone'],
 'locks': ['lox'],
 'lode': ['load'],
 'lone': ['loan'],
 'loo': ['lieu'],
 'loop': ['loupe'],
 'loot': ['lute'],
 'lore': ['law'],
 'loupe': ['loop'],
 'low': ['lo'],
 'lox': ['locks'],
 'lute': ['loot'],
 'lye': ['lie'],
 'lynx': ['links'],
 'lyre': ['liar'],
 'macintosh': ['mackintosh', 'mcintosh'],
 'mackintosh': ['macintosh', 'mcintosh'],
 'made': ['maid'],
 'magnate': ['magnet'],
 'magnet': ['magnate'],
 'magnificent': ['munificent'],
 'maid': ['made'],
 'mail': ['male'],
 'main': ['mane'],
 'maize': ['maze'],
 'male': ['mail'],
 'mall': ['maul'],
 'mane': ['main'],
 'manikin': ['mannequin'],
 'manna': ['manner', 'manor'],
 'mannequin': ['manikin'],
 'manner': ['manna', 'manor'],
 'manor': ['manna', 'manner'],
 'mantel': ['mantle'],
 'mantle': ['mantel'],
 'mare': ['mayor'],
 'marital': ['marshal', 'marshall', 'martial'],
 'mark': ['marque'],
 'marque': ['mark'],
 'marry': ['material', 'materiel', 'merry'],
 'marshal': ['marital', 'marshall', 'martial'],
 'marshall': ['marital', 'marshal', 'martial'],
 'marten': ['martian', 'martin'],
 'martial': ['marital', 'marshal', 'marshall'],
 'martian': ['marten', 'martin'],
 'martin': ['marten', 'martian'],
 'mask': ['masque'],
 'masque': ['mask'],
 'massed': ['mast'],
 'mast': ['massed'],
 'material': ['marry', 'materiel', 'merry'],
 'materiel': ['marry', 'material', 'merry'],
 'maul': ['mall'],
 'maw': ['moor', 'more'],
 'mayor': ['mare'],
 'maze': ['maize'],
 'mcintosh': ['macintosh', 'mackintosh'],
 'me': ['mi'],
 'mean': ['mien'],
 'meat': ['meet', 'mete'],
 'medal': ['meddle', 'metal', 'mettle'],
 'meddle': ['medal', 'metal', 'mettle'],
 'median': ['average', 'normal'],
 'meet': ['meat', 'mete'],
 'merry': ['marry', 'material', 'materiel'],
 'metal': ['medal', 'meddle', 'mettle'],
 'mete': ['meat', 'meet'],
 'meter': ['metre'],
 'metre': ['meter'],
 'mettle': ['medal', 'meddle', 'metal'],
 'mewl': ['mule'],
 'mews': ['muse'],
 'mi': ['me'],
 'mien': ['mean'],
 'might': ['mite'],
 'mil': ['mill'],
 'mill': ['mil'],
 'millinary': ['millinery'],
 'millinery': ['millinary'],
 'mince': ['mints'],
 'mind': ['mined'],
 'mined': ['mind'],
 'miner': ['minor', 'mynah'],
 'minor': ['miner', 'mynah'],
 'mints': ['mince'],
 'missal': ['missile'],
 'missed': ['mist'],
 'missile': ['missal'],
 'mist': ['missed'],
 'mite': ['might'],
 'moan': ['mown'],
 'moat': ['mote'],
 'mode': ['mowed'],
 'moor': ['maw', 'more'],
 'moose': ['mousse'],
 'more': ['maw', 'moor'],
 'morn': ['mourn'],
 'morning': ['mourning'],
 'mote': ['moat'],
 'mourn': ['morn'],
 'mourning': ['morning'],
 'mousse': ['moose'],
 'mouton': ['mutton'],
 'mowed': ['mode'],
 'mown': ['moan'],
 'mule': ['mewl'],
 'munificent': ['magnificent'],
 'muscle': ['mussel', 'muzzle'],
 'muse': ['mews'],
 'mussel': ['muscle', 'muzzle'],
 'mustard': ['mustered'],
 'mustered': ['mustard'],
 'mutton': ['mouton'],
 'muzzle': ['muscle', 'mussel'],
 'mynah': ['miner', 'minor'],
 'naval': ['navel'],
 'nave': ['knave'],
 'navel': ['naval'],
 'naw': ['gnaw', 'nor'],
 'nay': ['neigh'],
 'need': ['knead', 'kneed'],
 'neigh': ['nay'],
 'new': ['gnu', 'knew'],
 'nice': ['gneiss'],
 'nicks': ['nix'],
 'nigh': ['nye'],
 'night': ['knight'],
 'nit': ['knit'],
 'nix': ['nicks'],
 'no': ['know'],
 'nob': ['knob'],
 'nock': ['knock'],
 'none': ['nun'],
 'nor': ['gnaw', 'naw'],
 'normal': ['average', 'median'],
 'nose': ['knows'],
 'not': ['knot'],
 'nun': ['none'],
 'nye': ['nigh'],
 'oar': ['awe', 'oh', 'or', 'ore', 'owe'],
 'od': ['odd'],
 'odd': ['od'],
 'ode': ['owed'],
 'official': ['officious'],
 'officious': ['official'],
 'oh': ['awe', 'oar', 'or', 'ore', 'owe'],
 'one': ['won'],
 'or': ['awe', 'oar', 'oh', 'ore', 'owe'],
 'oracle': ['auricle'],
 'oral': ['aural'],
 'orc': ['auk'],
 'ore': ['awe', 'oar', 'oh', 'or', 'owe'],
 'oscillate': ['osculate'],
 'osculate': ['oscillate'],
 'ought': ['aught'],
 'our': ['hour'],
 'overdo': ['overdue'],
 'overdue': ['overdo'],
 'overseas': ['oversees'],
 'oversees': ['overseas'],
 'owe': ['awe', 'oar', 'oh', 'or', 'ore'],
 'owed': ['ode'],
 'paced': ['paste'],
 'packed': ['pact'],
 'packs': ['pax'],
 'pact': ['packed'],
 'paean': ['peon'],
 'pail': ['pale'],
 'pain': ['pane'],
 'pair': ['pare', 'pear'],
 'palate': ['palette', 'pallet'],
 'pale': ['pail'],
 'palette': ['palate', 'pallet'],
 'pall': ['pawl'],
 'pallet': ['palate', 'palette'],
 'paltry': ['poultry'],
 'pane': ['pain'],
 'parameter': ['perimeter'],
 'pare': ['pair', 'pear'],
 'parish': ['perish'],
 'pascal': ['paschal'],
 'paschal': ['pascal'],
 'passed': ['past'],
 'past': ['passed'],
 'paste': ['paced'],
 'paten': ['patten', 'pattern'],
 'patience': ['patients'],
 'patients': ['patience'],
 'patten': ['paten', 'pattern'],
 'pattern': ['paten', 'patten'],
 'pause': ['paws', 'pores', 'pours'],
 'pawl': ['pall'],
 'pawn': ['porn'],
 'paws': ['pause', 'pores', 'pours'],
 'pax': ['packs'],
 'pea': ['pee'],
 'peace': ['piece'],
 'peak': ['peek', 'peke', 'pique'],
 'peal': ['peel'],
 'pear': ['pair', 'pare'],
 'pearl': ['purl'],
 'pedal': ['peddle'],
 'peddle': ['pedal'],
 'pee': ['pea'],
 'peek': ['peak', 'peke', 'pique'],
 'peel': ['peal'],
 'peer': ['pier'],
 'peke': ['peak', 'peek', 'pique'],
 'peon': ['paean'],
 'peremptory': ['pre-emptory'],
 'perimeter': ['parameter'],
 'perish': ['parish'],
 'perquisite': ['prerequisite'],
 'persecute': ['prosecute'],
 'personal': ['personnel'],
 'personnel': ['personal'],
 'perspective': ['prospective'],
 'petit': ['petite', 'petty'],
 'petite': ['petit', 'petty'],
 'petty': ['petit', 'petite'],
 'phase': ['faze'],
 'phew': ['few'],
 'phi': ['fie'],
 'phial': ['file'],
 'phiz': ['fizz'],
 'phrase': ['frays'],
 'physic': ['physique', 'psychic'],
 'physique': ['physic', 'psychic'],
 'pi': ['pie'],
 'pica': ['pika'],
 'pie': ['pi'],
 'piece': ['peace'],
 'pier': ['peer'],
 'pika': ['pica'],
 'pique': ['peak', 'peek', 'peke'],
 'place': ['plaice'],
 'plaice': ['place'],
 'plain': ['plane'],
 'plait': ['plate'],
 'plane': ['plain'],
 'plate': ['plait'],
 'pleas': ['please'],
 'please': ['pleas'],
 'plum': ['plumb'],
 'plumb': ['plum'],
 'pole': ['poll'],
 'policy': ['polity'],
 'polity': ['policy'],
 'poll': ['pole'],
 'poof': ['pouffe'],
 'poor': ['pore', 'pour'],
 'poplar': ['popular'],
 'populace': ['populous'],
 'popular': ['poplar'],
 'populous': ['populace'],
 'pore': ['poor', 'pour'],
 'pores': ['pause', 'paws', 'pours'],
 'porn': ['pawn'],
 'pouffe': ['poof'],
 'poultry': ['paltry'],
 'pour': ['poor', 'pore'],
 'pours': ['pause', 'paws', 'pores'],
 'practice': ['practise'],
 'practise': ['practice'],
 'praise': ['prays', 'preys'],
 'pray': ['prey'],
 'prays': ['praise', 'preys'],
 'pre-emptory': ['peremptory'],
 'precede': ['proceed'],
 'prerequisite': ['perquisite'],
 'prescribe': ['proscribe'],
 'presence': ['presents'],
 'presentiment': ['presentment'],
 'presentment': ['presentiment'],
 'presents': ['presence'],
 'prey': ['pray'],
 'preys': ['praise', 'prays'],
 'pride': ['pried'],
 'pried': ['pride'],
 'pries': ['prize'],
 'primer': ['primmer'],
 'primmer': ['primer'],
 'prince': ['prints'],
 'principal': ['principle'],
 'principle': ['principal'],
 'prints': ['prince'],
 'prize': ['pries'],
 'proceed': ['precede'],
 'profit': ['prophet'],
 'prone': ['supine'],
 'prophecy': ['prophesy'],
 'prophesy': ['prophecy'],
 'prophet': ['profit'],
 'propose': ['purpose'],
 'proscribe': ['prescribe'],
 'prosecute': ['persecute'],
 'prospective': ['perspective'],
 'prostate': ['prostrate'],
 'prostrate': ['prostate'],
 'psychic': ['physic', 'physique'],
 'purl': ['pearl'],
 'purpose': ['propose'],
 'put': ['putt'],
 'putt': ['put'],
 'quarts': ['quartz'],
 'quartz': ['quarts'],
 'quay': ['key'],
 'quean': ['queen'],
 'queen': ['quean'],
 'queue': ['cue', 'kyu'],
 'quire': ['choir'],
 'rabbet': ['rabbit'],
 'rabbit': ['rabbet'],
 'rack': ['wrack'],
 'rain': ['reign', 'rein'],
 'raise': ['rays', 'raze'],
 'rap': ['rapped', 'rapt', 'wrap', 'wrapped'],
 'rapped': ['rap', 'rapt', 'wrap', 'wrapped'],
 'rapt': ['rap', 'rapped', 'wrap', 'wrapped'],
 'raw': ['roar'],
 'rays': ['raise', 'raze'],
 'raze': ['raise', 'rays'],
 'read': ['red', 'reed'],
 'real': ['reel'],
 'reality': ['realty'],
 'realty': ['reality'],
 'red': ['read', 'reed'],
 'reed': ['read', 'red'],
 'reek': ['wreak'],
 'reel': ['real'],
 'register': ['registrar'],
 'registrar': ['register'],
 'reign': ['rain', 'rein'],
 'rein': ['rain', 'reign'],
 'reluctant': ['reticent'],
 'residence': ['residents'],
 'residents': ['residence'],
 'rest': ['wrest'],
 'retch': ['wretch'],
 'reticent': ['reluctant'],
 'review': ['revue'],
 'revue': ['review'],
 'rheum': ['room'],
 'rho': ['roe', 'row'],
 'riffle': ['rifle'],
 'rifle': ['riffle'],
 'rigger': ['rigor'],
 'right': ['rite', 'wright', 'write'],
 'rigor': ['rigger'],
 'ring': ['wring'],
 'rite': ['right', 'wright', 'write'],
 'road': ['rode', 'rowed'],
 'roar': ['raw'],
 'rode': ['road', 'rowed'],
 'roe': ['rho', 'row'],
 'roil': ['royal'],
 'role': ['roll'],
 'roll': ['role'],
 'roo': ['roux', 'rue'],
 'rood': ['rude', 'rued'],
 'room': ['rheum'],
 'roomer': ['rumour'],
 'root': ['route'],
 'rose': ['rouse', 'rows'],
 'rota': ['rotor'],
 'rote': ['wrote'],
 'rotor': ['rota'],
 'rough': ['ruff'],
 'rouse': ['rose', 'rows'],
 'route': ['root'],
 'roux': ['roo', 'rue'],
 'row': ['rho', 'roe'],
 'rowed': ['road', 'rode'],
 'rows': ['rose', 'rouse'],
 'royal': ['roil'],
 'rude': ['rood', 'rued'],
 'rue': ['roo', 'roux'],
 'rued': ['rood', 'rude'],
 'ruff': ['rough'],
 'ruin': ['rune'],
 'rumour': ['roomer'],
 'rune': ['ruin'],
 'rung': ['wrung'],
 'rye': ['wry'],
 'sac': ['sack'],
 'sachet': ['sashay'],
 'sack': ['sac'],
 'sail': ['sale'],
 'sale': ['sail'],
 'sane': ['seine'],
 'sanitarium': ['sanitorium'],
 'sanitorium': ['sanitarium'],
 'sashay': ['sachet'],
 'satire': ['satyr'],
 'satyr': ['satire'],
 'sauce': ['source'],
 'saver': ['savour'],
 'savour': ['saver'],
 'saw': ['sew', 'so', 'soar', 'sore', 'sow'],
 'scene': ['seen'],
 'scent': ['cent', 'sent'],
 'scull': ['skull'],
 'sea': ['see'],
 'sealing': ['ceiling'],
 'seam': ['seem'],
 'seaman': ['semen'],
 'sear': ['seer', 'sere'],
 'seas': ['sees', 'seize'],
 'see': ['sea'],
 'seed': ['cede'],
 'seem': ['seam'],
 'seen': ['scene'],
 'seer': ['sear', 'sere'],
 'sees': ['seas', 'seize'],
 'seine': ['sane'],
 'seize': ['seas', 'sees'],
 'sell': ['cell'],
 'seller': ['cellar'],
 'semen': ['seaman'],
 'sense': ['census'],
 'sensor': ['censer', 'censor', 'censure'],
 'sent': ['cent', 'scent'],
 'sere': ['sear', 'seer'],
 'serf': ['surf'],
 'serge': ['surge'],
 'serial': ['cereal'],
 'session': ['cession'],
 'sew': ['saw', 'so', 'soar', 'sore', 'sow'],
 'shake': ['sheikh'],
 'shanty': ['chantey'],
 'shear': ['shearn', 'sheer'],
 'shearn': ['shear', 'sheer'],
 'sheer': ['shear', 'shearn'],
 'sheik': ['chic'],
 'sheikh': ['shake'],
 'shoe': ['shoo'],
 'shone': ['shown'],
 'shoo': ['shoe'],
 'shoot': ['chute'],
 'shown': ['shone'],
 'sic': ['sick'],
 'sick': ['sic'],
 'side': ['sighed'],
 'sighed': ['side'],
 'sighs': ['size'],
 'sight': ['cite', 'site'],
 'sign': ['sine'],
 'signet': ['cygnet'],
 'sine': ['sign'],
 'sink': ['synch'],
 'site': ['cite', 'sight'],
 'size': ['sighs'],
 'skull': ['scull'],
 'slay': ['sleigh'],
 'sleigh': ['slay'],
 'sleight': ['slight'],
 'slight': ['sleight'],
 'sloe': ['slow'],
 'slow': ['sloe'],
 'so': ['saw', 'sew', 'soar', 'sore', 'sow'],
 'soar': ['saw', 'sew', 'so', 'sore', 'sow'],
 'soared': ['sward', 'sword'],
 'sol': ['sole', 'soul'],
 'sold': ['soled'],
 'sole': ['sol', 'soul'],
 'soled': ['sold'],
 'some': ['sum'],
 'son': ['sun'],
 'sore': ['saw', 'sew', 'so', 'soar', 'sow'],
 'sort': ['sought'],
 'sought': ['sort'],
 'soul': ['sol', 'sole'],
 'source': ['sauce'],
 'sow': ['saw', 'sew', 'so', 'soar', 'sore'],
 'spa': ['spar'],
 'spade': ['spayed'],
 'spar': ['spa'],
 'spayed': ['spade'],
 'spoor': ['spore'],
 'spore': ['spoor'],
 'staid': ['stayed'],
 'stair': ['stare'],
 'stairs': ['stares'],
 'stake': ['steak'],
 'stalk': ['stork'],
 'stare': ['stair'],
 'stares': ['stairs'],
 'stationary': ['stationery'],
 'stationery': ['stationary'],
 'stayed': ['staid'],
 'steak': ['stake'],
 'steal': ['steel'],
 'steel': ['steal'],
 'step': ['steppe'],
 'steppe': ['step'],
 'stile': ['sty', 'style'],
 'storey': ['story'],
 'stork': ['stalk'],
 'story': ['storey'],
 'straight': ['strait'],
 'strait': ['straight'],
 'sty': ['stile', 'style'],
 'style': ['stile', 'sty'],
 'succour': ['sucker'],
 'sucker': ['succour'],
 'suit': ['suite', 'sweet'],
 'suite': ['suit', 'sweet'],
 'sum': ['some'],
 'summary': ['summery'],
 'summery': ['summary'],
 'sun': ['son'],
 'supine': ['prone'],
 'surf': ['serf'],
 'surge': ['serge'],
 'sward': ['soared', 'sword'],
 'swat': ['swot'],
 'sweet': ['suit', 'suite'],
 'sword': ['soared', 'sward'],
 'swot': ['swat'],
 'symbol': ['cymbal', 'cymbol'],
 'synch': ['sink'],
 'tacet': ['tacit'],
 'tacit': ['tacet'],
 'tacked': ['tact'],
 'tacks': ['tax'],
 'tact': ['tacked'],
 'tail': ['tale'],
 'take': ['bring'],
 'tale': ['tail'],
 'talesman': ['talisman'],
 'talisman': ['talesman'],
 'talk': ['torque'],
 'taper': ['tapir'],
 'tapir': ['taper'],
 'tare': ['tear', 'tier'],
 'tasteful': ['tasty'],
 'tasty': ['tasteful'],
 'taught': ['taut', 'tort'],
 'taupe': ['tope'],
 'taut': ['taught', 'tort'],
 'tax': ['tacks'],
 'te': ['tea', 'tee'],
 'tea': ['te', 'tee'],
 'team': ['teem'],
 'tear': ['tare', 'tier'],
 'teas': ['tease'],
 'tease': ['teas'],
 'tee': ['te', 'tea'],
 'teem': ['team'],
 'tense': ['tents'],
 'tents': ['tense'],
 'terce': ['terse'],
 'tern': ['turn'],
 'terse': ['terce'],
 'than': ['then'],
 'their': ['there', "they're"],
 'then': ['than'],
 'there': ['their', "they're"],
 "they're": ['their', 'there'],
 'threw': ['through'],
 'throe': ['throw'],
 'throes': ['throws'],
 'throne': ['thrown'],
 'through': ['threw'],
 'throw': ['throe'],
 'thrown': ['throne'],
 'throws': ['throes'],
 'thyme': ['time'],
 'tic': ['tick'],
 'tick': ['tic'],
 'tide': ['tied'],
 'tied': ['tide'],
 'tier': ['tare', 'tear'],
 'time': ['thyme'],
 'tire': ['tyre'],
 'to': ['toe', 'too', 'tow', 'two'],
 'toad': ['toed', 'towed'],
 'tocsin': ['toxin'],
 'toe': ['to', 'too', 'tow', 'two'],
 'toed': ['toad', 'towed'],
 'told': ['tolled'],
 'tole': ['toll'],
 'toll': ['tole'],
 'tolled': ['told'],
 'ton': ['tun'],
 'too': ['to', 'toe', 'tow', 'two'],
 'tool': ['tulle'],
 'tope': ['taupe'],
 'tor': ['tore'],
 'tore': ['tor'],
 'torque': ['talk'],
 'tort': ['taught', 'taut'],
 'tortuous': ['torturous'],
 'torturous': ['tortuous'],
 'tough': ['tuff'],
 'tow': ['to', 'toe', 'too', 'two'],
 'towed': ['toad', 'toed'],
 'toxin': ['tocsin'],
 'track': ['tracked', 'tract'],
 'tracked': ['track', 'tract'],
 'tract': ['track', 'tracked'],
 'tray': ['trey'],
 'trey': ['tray'],
 'troop': ['troupe'],
 'troupe': ['troop'],
 'trussed': ['trust'],
 'trust': ['trussed'],
 'trustee': ['trusty'],
 'trusty': ['trustee'],
 'tuba': ['tuber'],
 'tuber': ['tuba'],
 'tuff': ['tough'],
 'tulle': ['tool'],
 'tun': ['ton'],
 'turban': ['turbine'],
 'turbine': ['turban'],
 'turn': ['tern'],
 'two': ['to', 'toe', 'too', 'tow'],
 'tyre': ['tire'],
 'undo': ['undue'],
 'undue': ['undo'],
 'up': ['upped'],
 'upped': ['up'],
 'urn': ['earn'],
 'use': ['ewes', 'yews'],
 'vain': ['vane', 'vein'],
 'valance': ['valence'],
 'vale': ['veil'],
 'valence': ['valance'],
 'vane': ['vain', 'vein'],
 'vary': ['very'],
 'veil': ['vale'],
 'vein': ['vain', 'vane'],
 'veracious': ['voracious'],
 'very': ['vary'],
 'vial': ['vile', 'viol'],
 'vice': ['vise'],
 'vicious': ['viscous', 'viscus'],
 'vile': ['vial', 'viol'],
 'villain': ['villein'],
 'villein': ['villain'],
 'viol': ['vial', 'vile'],
 'virtu': ['virtue'],
 'virtue': ['virtu'],
 'viscous': ['vicious', 'viscus'],
 'viscus': ['vicious', 'viscous'],
 'vise': ['vice'],
 'voracious': ['veracious'],
 'wade': ['weighed'],
 'wail': ['wale', 'whale'],
 'wain': ['wane'],
 'waist': ['waste'],
 'wait': ['weight'],
 'waive': ['wave'],
 'wale': ['wail', 'whale'],
 'wall': ['waul'],
 'wane': ['wain'],
 'want': ['wont'],
 'war': ['wore'],
 'ware': ['wear', 'where'],
 'wares': ['wears'],
 'warn': ['worn'],
 'wart': ['wort'],
 'waste': ['waist'],
 'watt': ['what'],
 'waul': ['wall'],
 'wave': ['waive'],
 'wax': ['whacks'],
 'way': ['weigh', 'whey'],
 'we': ['wee', 'whee'],
 "we'd": ['weed'],
 "we'll": ['weal', 'wheel'],
 "we're": ['weir'],
 'weak': ['week'],
 'weal': ["we'll", 'wheel'],
 'wean': ['ween'],
 'wear': ['ware', 'where'],
 'wears': ['wares'],
 'weather': ['wether', 'whether'],
 'weaver': ['weever'],
 'wee': ['we', 'whee'],
 'weed': ["we'd"],
 'week': ['weak'],
 'ween': ['wean'],
 'weever': ['weaver'],
 'weigh': ['way', 'whey'],
 'weighed': ['wade'],
 'weight': ['wait'],
 'weir': ["we're"],
 'were': ['whirr'],
 'wet': ['whet'],
 'wether': ['weather', 'whether'],
 'whacks': ['wax'],
 'whale': ['wail', 'wale'],
 'what': ['watt'],
 'wheald': ['wheeled'],
 'whee': ['we', 'wee'],
 'wheel': ["we'll", 'weal'],
 'wheeled': ['wheald'],
 'where': ['ware', 'wear'],
 'whet': ['wet'],
 'whether': ['weather', 'wether'],
 'whey': ['way', 'weigh'],
 'which': ['witch'],
 'whig': ['wig'],
 'while': ['wile'],
 'whine': ['wine'],
 'whirl': ['whorl'],
 'whirled': ['world'],
 'whirr': ['were'],
 'whit': ['wit'],
 'white': ['wight'],
 'whither': ['wither'],
 "who''s": ["who's", 'whose'],
 "who's": ["who''s", 'whose'],
 'whoa': ['woe'],
 'whole': ['hole'],
 'wholly': ['holey', 'holy'],
 'whoop': ['hoop'],
 'whore': ['haw', 'hoar'],
 'whorl': ['whirl'],
 'whose': ["who''s", "who's"],
 'wig': ['whig'],
 'wight': ['white'],
 'wile': ['while'],
 'wine': ['whine'],
 'wit': ['whit'],
 'witch': ['which'],
 'wither': ['whither'],
 'woe': ['whoa'],
 'won': ['one'],
 'wont': ['want'],
 'wood': ['would'],
 'wore': ['war'],
 'world': ['whirled'],
 'worn': ['warn'],
 'worst': ['wurst'],
 'wort': ['wart'],
 'would': ['wood'],
 'wrack': ['rack'],
 'wrap': ['rap', 'rapped', 'rapt', 'wrapped'],
 'wrapped': ['rap', 'rapped', 'rapt', 'wrap'],
 'wreak': ['reek'],
 'wrest': ['rest'],
 'wretch': ['retch'],
 'wright': ['right', 'rite', 'write'],
 'wring': ['ring'],
 'write': ['right', 'rite', 'wright'],
 'wrote': ['rote'],
 'wrung': ['rung'],
 'wry': ['rye'],
 'wurst': ['worst'],
 'yaw': ['yore', "you''re", "you're", 'your'],
 'yew': ['ewe', 'you'],
 'yews': ['ewes', 'use'],
 'yoke': ['yolk'],
 'yolk': ['yoke'],
 'yore': ['yaw', "you''re", "you're", 'your'],
 'you': ['ewe', 'yew'],
 "you''re": ['yaw', 'yore', "you're", 'your'],
 "you'll": ['yule'],
 "you're": ['yaw', 'yore', "you''re", 'your'],
 'your': ['yaw', 'yore', "you''re", "you're"],
 'yule': ["you'll"]}